### ISSUE TITLE
Workers with long processes that interrupt the main thread time out the RabbitMQ connection

### ISSUE THREAD

**Issue by Janwillemtv** [CLARIAH/DANE-utils#1]
With long analysis tasks, the main thread is busy for a while. The heartbeat nature of RabbitMQ makes that after some time the RabbitMQ server closes the connection to the worker. Because the analysis task is done in the same thread as the pika client loses its ability to send a heartbeat to the RabbitMQ server.
That's why it seems handy to implement the analysis task in a different thread. This [example](https://github.com/pika/pika/blob/1.0.1/examples/basic_consumer_threaded.py) shows that its possible to use different threads for the analysis tasks and this should solve the problem of timing out the connection on long tasks.

**Comment by Nanne** [comment]
Closed and re-opened in internal issue board.
